### ISSUE TITLE
usage understanding

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/shinobi#5]
I'm trying to put to words how this works.

I originally thought that this was set up such as:
- Roles: Admin, User, Guest
- Permissions: Create, View, Update, Destroy

However, going through the docs it seems that I haven't gotten the premiss of how this works.

Is it?
- Permissions:  Access, Manage, ???
- Roles == Models; user, blog, task, todo +++

Also, just wondering ... I created roles and permission controllers so that I can have a web interface for these. Should I extend the roles, and permission models based on yours?

And ..
I did have an issue of access the package models since I had the trait attached to the model but I'm using a repository and had to include it.

Hope you don't mind checking my homework :blush:

**Comment by kaidesu** [comment]
Your original thought/assumption is correct. Roles can be "User", "Moderator", "Administrator", etc.

And yes, you may extend the role and permission models for use with your own model/repository set up - this is pretty much required as the relationships between everything are defined in the models provided by Shinobi.

Not sure I completely follow your last statement - because everything is Namespaced, you'll always need to point to class locations either through the `use` statement or reference the full namespace path of the class (e.g. `\Caffeinated\Shinobi\Traits\ShinobiTrait`). Otherwise PHP thinks you're referencing a file within the same directory as the one it's currently in.

**Comment by illuminate3** [comment]
What about the permissions?

Actually, this is what confused me:
```
'access.admin'
```

if my original understanding was correct is that "permission:role" ?

I was up for too long and understanding just went out the door. Which means I probably pooched the namespace.

Thanks!

**Comment by kaidesu** [comment]
Permissions can be called and follow any convention you like as well :) they're just slugs linking to any given action you wish to check for. I personally try to use a simple verb/group approach:

`create.user` or `create_user`, following a `verb_group` convention.

So in that example, a "group" could be a reference to a module (aka, a users module), wheres the "verb" links to the *action* being taken (e.g. creating a user).

Usage would be:

```php
Auth::user()->can('create_user');
```

This would return either `true` or `false` depending on if the role associated with the user has the given permission.

But again, permissions can be called whatever you like that makes sense to you.

**Comment by illuminate3** [comment]
Ah! I get it now. Thanks!
The dot threw me off. I was thinking in routes/views/config/trans dot usage.

Also, I was adding 1 more separate layer into this: role::model::permission (role : verb : group) and in turn was making things difficult for myself.

So, thinking out loud, I should just be doing role::permission_model (role : verb_group) <--makes sense now

Thanks!
