### ISSUE TITLE
Traits error

### ISSUE THREAD

**Issue by samuelecarpene** [caffeinated/shinobi#66]
In version 3.1 i get an error using traits methods

 Call to protected method Caffeinated\Shinobi\Traits\ShinobiTrait::getShinobiTag() from context 'Caffeinated\Shinobi\Models\Role'

this is when i use method syncPermissions from Role model.

**Comment by mdxshana** [comment]
I do not know why the error, first think about modifying a bit and pass that protected function to public, and then I get another error that a method does not exist, and looking carefully the method does not exist, so I decided to comment this line of code in the PermissionTrait calse and it works

` public function assignPermission($permissionId = null)
    {
        $permissions = $this->permissions;

        if (!$permissions->contains($permissionId)) {
            //$this->flushPermissionCache();  this is the one that comments

            return $this->permissions()->attach($permissionId);
        }

        return false;
    }`

**Comment by johnhearfield** [comment]
The error is on line 66 of /src/Models/Role.php
`
parent::flushPermissionCache([
          static::getShinobiTag(),
          \Caffeinated\Shinobi\Traits\ShinobiTrait::getShinobiTag()
        ]);
`

Its trying to reference getShinboTag which is private static, and since Role doesnt use ShinboTrait it doesn't have access. Using the trait would cause issues because each has its own getShinobiTag()

**Comment by psoots** [comment]
I think the idea here is that when updating a role, we need to clear the cache for both the `'shinobi.roles'` tag and the `'shinobi.users'` tag, but the users tag is on a class owned by the client. We don't actually have a model that uses`ShinobiTrait` that provides the `'shinboi.users'` tag, so invoking the trait directly hops around that. 

If the idea is to allow client code to adjust these tags, this `Role::flushPermissionCache` method is just going to ignore the client's settings. Mission not accomplished. 

My suggestion would be to: 

1. Make `ShinobiTrait::getShinobiTag` public so the `Role` class can access it. 
2. In `Role::flushPermissionCache` get the user model from config (like we do elsewhere) and then invoke our `getShinobiTrait` method on that class instead of calling it on the trait directly.

---

I didn't realize you could call static trait methods directly. It's just static, so it makes sense that it's possible, but it breaks down the paradigm of using traits to add behaviors to classes if you're just going to bypass those classes and hit the traits directly. As much as I hate the phrase, this is definitely a "bad code smell." There is usually a cleaner way.
